version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
        - 27018:27017
    environment:
        - MONGO_DATA_DIR=/var/lib/data/db
        - MONGO_LOG_DIR=/dev/null
    volumes:
        - mongo-data:/usr/src/db
  bot:
    build: .
    links:
        - mongo
    volumes:
        - bot-data:/usr/src/app
  web:
    build: ./api
    restart: always
    ports:
      - 5000:5000
    volumes:
      - web-data:/usr/src/web
    links:
      - mongo
volumes:
  mongo-data:
  bot-data:
  web-data:
