FROM python:3.7.5-alpine3.10


WORKDIR /usr/src/app

COPY requirements_bot.txt ./

RUN pip install --upgrade pip
RUN pip install -r requirements_bot.txt


COPY . .

CMD [ "python3", "-u", "./main.py" ]
