version: '3.1'
services:

  postgre:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: yumebot
      POSTGRES_DB : yumebot
    volumes:
      - db-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"

  bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_bot
    links:
        - postgre
    volumes:
        - .:/usr/src/app
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "3"

volumes:
 db-data:
  driver: local