version: '3'
services:
  mongo:
    image: mongo:3.6.11
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongodb:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
  bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_bot
    links:
        - mongo

  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_web
    ports:
      - 4437:4437
    restart: always

    links:
      - mongo
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"

