version: '3'
services:
  mongo:
    image: mongo:4.0.5
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongodb:/data/db
  bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_bot
    links:
        - mongo
    #volumes:
    #    - .:/usr/src/app
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_web
    ports:
      - 4437:4437
    restart: always
    #volumes:
    #    - .:/usr/src/web
    links:
      - mongo

