version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
        - 27018:27017
    environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
    volumes:
        - ./data/db:/data/db
  bot:
    build: .
    links:
        - mongo
    volumes:
        - .:/usr/src/app
